### PR TITLE
upgrades & build using tsup

### PR DESCRIPTION
**Pull request by ndelangen**
Closes: https://github.com/storybookjs/storybook/issues/25130

<details>
  <summary>📦 Published PR as canary version: <code>3.0.0--canary.84.e8a1f80.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/addon-console@3.0.0--canary.84.e8a1f80.0
  # or 
  yarn add @storybook/addon-console@3.0.0--canary.84.e8a1f80.0
  ```
</details>

### CODE REVIEW

**Comment by ndelangen** [comment]
@SocketSecurity ignore @sinclair/typebox@0.27.8
@SocketSecurity ignore @storybook/addon-links@7.6.7
@SocketSecurity ignore @storybook/manager@7.6.7
@SocketSecurity ignore @storybook/preview@7.6.7
@SocketSecurity ignore es-iterator-helpers@1.0.15
@SocketSecurity ignore load-tsconfig@0.2.5
@SocketSecurity ignore tsup@8.0.1
@SocketSecurity ignore assert@2.1.0
@SocketSecurity ignore react@18.2.0
@SocketSecurity ignore hasown@2.0.0
@SocketSecurity ignore defaults@1.0.4
@SocketSecurity ignore array-equal@1.0.2
@SocketSecurity ignore handlebars@4.7.8
@SocketSecurity ignore is-async-function@2.0.0
@SocketSecurity ignore source-map@0.8.0-beta.0
@SocketSecurity ignore loupe@2.3.7
@SocketSecurity ignore fast-diff@1.3.0
@SocketSecurity ignore get-stream@8.0.1
@SocketSecurity ignore component-emitter@1.3.1
@SocketSecurity ignore foreground-child@3.1.1

**Comment by ndelangen** [comment]
@shilman Should I add `auto` to this repo, label it `major` and just go for it?

**Comment by valentinpalkovic** [comment]
@ndelangen, @shilman What's the status of this PR? Can we merge it?

**Comment by shilman** [comment]
@ndelangen works for me

**Comment by ndelangen** [comment]
@SocketSecurity ignore npm/defaults@1.0.4
@SocketSecurity ignore npm/is-async-function@2.0.0
@SocketSecurity ignore npm/react@18.2.0
@SocketSecurity ignore npm/foreground-child@3.1.1
@SocketSecurity ignore npm/fast-diff@1.3.0
@SocketSecurity ignore npm/tree-kill@1.2.2
@SocketSecurity ignore npm/source-map@0.8.0-beta.0
@SocketSecurity ignore npm/handlebars@4.7.8
@SocketSecurity ignore npm/assert@2.1.0
@SocketSecurity ignore npm/get-stream@8.0.1
@SocketSecurity ignore npm/loupe@2.3.7
@SocketSecurity ignore npm/hasown@2.0.0
@SocketSecurity ignore npm/array-equal@1.0.2
@SocketSecurity ignore npm/component-emitter@1.3.1
@SocketSecurity ignore npm/tsup@8.0.1
@SocketSecurity ignore npm/@storybook/addon-actions@7.6.7
@SocketSecurity ignore npm/@storybook/addon-links@7.6.7
@SocketSecurity ignore npm/@storybook/preview@7.6.7

**Comment by ndelangen** [comment]
@SocketSecurity ignore npm/supports-hyperlinks@2.3.0
@SocketSecurity ignore npm/requireg@0.2.2
@SocketSecurity ignore npm/bottleneck@2.19.5
@SocketSecurity ignore npm/signale@1.4.0
@SocketSecurity ignore npm/gitlog@4.0.8
@SocketSecurity ignore npm/@auto-it/core@11.0.4
@SocketSecurity ignore npm/@auto-it/npm@11.0.4

**Pull request merged**
